spring.application.name=users-service
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/RabitTel_Users?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# JPA commun
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true


server.servlet.context-path=/
spring.main.allow-circular-references=true


# Désactiver Cloud pour le développement local
spring.cloud.config.enabled=false
spring.cloud.discovery.enabled=true
spring.cloud.config.import-check.enabled=false


eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

jwt.secret=9873f537fc7413266284f025cd56f1064d3fd6f6c2abca257ecc65563eefc102
jwt.expiration=86400000